language: go
sudo: required
addons:
  apt:
    packages:
    - libtool
    - cmake
    - realpath
    - automake
    - ninja-build
    - curl
go:
- '1.10'

before_script:
- bash install_prerequisites.sh

script:
- go get github.com/bazelbuild/buildtools/buildifier
- bazel build //source/exe:envoy-static
- ls -al

