language: bash
sudo: required

services: 
  - docker

before_script:
- docker pull envoyproxy/envoy:latest
- docker run --rm -d -p 10000:10000 envoyproxy/envoy:latest

script:
- curl -v localhost:10000

